### ISSUE TITLE
Improve ndjson-map documentation

### ISSUE THREAD

**Issue by aendra-rininsland** [mbostock/ndjson-cli#18]
I've found `ndjson-cli` to be really useful in the context of dealing with ElasticSearch records, which bulk import in ndjson format. One task I frequently find myself needing to do (and which might also be relevant for handling ndjson in the context of topojson files) is to add a constant to each record.

I've found you can do this with the following syntax:

```
cat output.ldj | ndjson-map 'd["@imported-from"] = "file-dump", d'
```

But it took me a bit of experimenting to figure that out. Might it be worth adding a few notes on syntax to the README, or perhaps the cli `--help` docs? Happy to contribute if so!

**Comment by mbostock** [comment]
Yes. I welcome documentation improvements. Please send a PR and we can discuss.
