### ISSUE TITLE
Support for left joins

### ISSUE THREAD

**Issue by reubenfb** [mbostock/ndjson-cli#21]
Right now it seems like ndjson-join always does an inner join, and will delete features that are not shared between the two files. But it's very common for an external dataset to be missing data for some features (counties, states, etc.) that you still want to display in your final map.

Could ndjson-join take a parameter to support some outer joins? For a left join where a feature was missing in the "right" file, I'd imagine that d[1] could be and empty string or simply non-existent.

Apologies if this is already possible!

**Comment by mbostock** [comment]
A `--left` and `--right` argument, and emitting null for d₀ or d₁, respectively, in [d₀, d₁] sounds reasonable.
