### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ghost** [mbostock/ndjson-cli#25]
How to reproduced:

I'm trying to execute this example:
https://bl.ocks.org/mbostock/c57be63169694093cca028194068ea3b

but i can not because of this: https://github.com/substack/shp2json/issues/23

So, i modify the code, to not used shp2json, in that way:
```

# Download.
curl -z build/estados.zip -o build/estados.zip http://mapserver.inegi.org.mx/MGN/mge2010v5_0.zip
# Decompress.
unzip -od build build/estados.zip

#Convert the shape file to GeoJSON:
ogr2ogr -f GeoJSON build/states.json build/Entidades_2010_5.shp

#Now use the ndjson-map in the same way from a cat of the GeoJson file:
cat build/states.json | ndjson-map -r d3=d3-geo 'p = d3.geoIdentity().reflectY(true).fitExtent([[10, 10], [960 - 10, 600 - 10]], d), "d3.geoIdentity().reflectY(true).scale(" + p.scale() + ").translate([" + p.translate() + "])"'
```

but it resulting in:
```
stdin:1
{
^
SyntaxError: Unexpected end of JSON input
```
My data:
lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	LMDE 2 Betsy
Release:	2
Codename:	betsy

node --version
v6.11.2

ogr2ogr --version
GDAL 1.10.1, released 2013/08/26

ndjson-map --version
0.3.1

**Comment by ghost** [comment]
So, probably you can embed the shp2json inside your own project, fork it, or add an option to load a geojson from a file directly, because the last update of shp2json was a year ago and not appear to be an active project. 

**Note:** The error with _cat_ appear to be that the resulting json is to big to be loaded using cat.

**Comment by ghost** [comment]
Ok, that was that i installed a wrong package. i install shp2json instead of your shapefile. With your shape file it work... Anyway, please considered to add an option to load a geojson file instead of work from an stream...

**Comment by aboutaaron** [comment]
~I've run into the same error. It'd be nice to just load a geojson file instead of always working form a shapefile-to-json stream via shp2json. In my case, I'm working with a csv of points that I'm convert to geojson for mapping.~

Turns out I just need to use `ndjson-cat` first and then pipe it to `ndjson-split`.
