### ISSUE TITLE
ndjson-sort returns only the features

### ISSUE THREAD

**Issue by petulla** [mbostock/ndjson-cli#26]
hey there

I'm working off of the census House map at this link [here](https://www.census.gov/geo/maps-data/data/cbf/cbf_cds.html) (cb_2016_us_cd115_500k.zip).

My command is--> `shp2json -n cb_2016_us_cd115_500k.shp | ndjson-sort 'a.properties.GEOID.localeCompare(b.properties.GEOID)' > us-house.json`

I'm index sorting the GEOIDs for faster lookup in another application.

The command is only outputting the map features, one per line, with no comma separation between the objects. The bbox etc are all stripped out.

**Comment by mbostock** [comment]
You need to use ndjson-reduce to wrap the features in a FeatureCollection as described in the README. shp2json -n generates a sequence of features; ndjson-sort reorders that sequence; then ndjson-reduce puts them back into a collection.

**Comment by mbostock** [comment]
If you prefer you can use shp2json without -n and then ndjson-map on the entire collection to sort the features:

```
shp2json input.shp | ndjson-map 'd.features.sort(…), d' > output.json
```

**Comment by petulla** [comment]
Got it, thanks for the tip on -map and I see the reduce step now.
