### ISSUE TITLE
Support --unquoted output for ndjson-map

### ISSUE THREAD

**Issue by stevage** [mbostock/ndjson-cli#31]
There doesn't seem to be a way to use ndjson-map to transform JSON values into raw strings that aren't wrapped in double quotes.

Maybe an option like `--unquoted`:

```
echo '{ "foo": "blah" }' | ndjson-map --unquoted d.foo
blah
```

I'm not sure there are any other types where this is an issue: numbers, arrays, booleans, nulls, objects should probably always be output as currently. Any non-standard output could be achieved by transforming to a string, and then using this option.

**Comment by mbostock** [comment]
ndjson-cli works exclusively with newline-delimited JSON. If you want to convert to something that’s not JSON, I suggest you write a separate program and pipe the output of ndjson-cli to that.

**Comment by stevage** [comment]
>ndjson-cli works exclusively with newline-delimited JSON.

Sure, but an operation to transform from ndjson to the simplest possible not-ndjson format seems within scope to me.

> I suggest you write a separate program and pipe the output of ndjson-cli to that.

Yeah, and sadly that's the only workaround. A whole new program to write, package, distribute, remember what it was called etc, rather than 4 lines of Javascript here. :/
