### ISSUE TITLE
ndjson-split output is blank

### ISSUE THREAD

**Issue by smtl** [mbostock/ndjson-cli#32]
I am following along this tutorial: https://medium.com/@mbostock/command-line-cartography-part-2-c3a82c5c0f3

ndjson-split 'd.features' < ca-albers.json | output.ndjson

gives a blank file. ca-albers.json is a file with features in it.

**Comment by smtl** [comment]
User error - after regenerating my source file, it works

**Comment by mbostock** [comment]
I think you want `>` not `|` in your command, also.

```
ndjson-split 'd.features' < ca-albers.json > output.ndjson
```
