### ISSUE TITLE
Question regarding filtering

### ISSUE THREAD

**Issue by uswoods** [mbostock/ndjson-cli#34]
(Cross-post from https://gis.stackexchange.com/questions/298144/filter-geojson-by-with-ndjson )

I would like to filter a GeoJSON with pipelines by the properties diameter and type (gas/oil):

    {"type":"Feature","properties":{"OPERATOR":"CENTERPOINT ENERGY INTRA P/L,LLC","CONTACT_PHONE_NUMBER":"2819600076","COMMODITY_DESCRIPTION":"NATURAL GAS","SYSTEM_NAME":"102","SUBSYSTEM_NAME":"IGS SYSTEM","DIAMETER":10.75,"T4PERMIT":"03755","T4PERMIT_MILES":0.17,"TYPE":"NATURAL GAS","INTERSTATE":"No","SYSTEM_TYPE":"Gas Transmission              ","STATUS":"In Service","COUNTY_FIPS":"201","OBJECTID":114027,"COUNTY_NAME":"HARRIS","SHAPE.LEN":893.364654362696,"P5_NUM":"141067"},"geometry":{"type":"LineString","coordinates":[[-95.21162248240012,29.809304236846675],[-95.21188396247372,29.809229064820354],[-95.21213367287471,29.809216873014062],[-95.21253903873001,29.809090744025184],[-95.21428860240415,29.808534857775637]],"bbox":[-95.21428860240415,29.808534857775637,-95.21162248240012,29.809304236846675]}}
    {"type":"Feature","properties":{"OPERATOR":"CENTERPOINT ENERGY INTRA P/L,LLC","CONTACT_PHONE_NUMBER":"2819600076","COMMODITY_DESCRIPTION":"NATURAL GAS","SYSTEM_NAME":"102","SUBSYSTEM_NAME":"IGS SYSTEM","DIAMETER":14,"T4PERMIT":"03755","T4PERMIT_MILES":0.72,"TYPE":"NATURAL GAS","INTERSTATE":"No","SYSTEM_TYPE":"Gas Transmission              ","STATUS":"In Service","COUNTY_FIPS":"201","OBJECTID":114028,"COUNTY_NAME":"HARRIS","SHAPE.LEN":3816.63490489555,"P5_NUM":"141067"},"geometry":{"type":"LineString","coordinates":[[-95.22946208114293,29.74733103507275],[-95.22730678727892,29.74736645770293],[-95.22697222682558,29.74738420770742],[-95.22619495077038,29.74739703963204],[-95.2256267402878,29.74741726953456],[-95.2251207496631,29.747439244223912],[-95.22454696130762,29.747516679799684],[-95.22400349999367,29.747569300304647],[-95.22396883251615,29.7475741127291],[-95.22391307079606,29.747581851133376],[-95.22354516023839,29.747846246752985],[-95.22323050181615,29.747754044689554],[-95.22297271764369,29.74765347102593],[-95.2228425411359,29.747664902158586],[-95.22214615184606,29.74773584988962],[-95.22188590793394,29.747755685837003],[-95.22138062865608,29.747898445049255],[-95.22099956452766,29.748003944007852],[-95.22067291708576,29.74808833541714],[-95.22017806203013,29.74818307157069],[-95.21889922086419,29.748424777644107],[-95.2178592681016,29.748662637063198],[-95.21774062648129,29.7486894877378]],"bbox":[-95.22946208114293,29.74733103507275,-95.21774062648129,29.7486894877378]}}
    {"type":"Feature","properties":{"OPERATOR":"SHERIDAN PRODUCTION COMPANY, LLC","CONTACT_PHONE_NUMBER":"7135481027","COMMODITY_DESCRIPTION":"NATURAL GAS","SYSTEM_NAME":"STOCKMAN SYSTEM (TRANSFERRED FROM 07825)","SUBSYSTEM_NAME":"JONES #2 : SWGP","DIAMETER":0,"T4PERMIT":"09371","T4PERMIT_MILES":0,"TYPE":"NATURAL GAS","INTERSTATE":"No","SYSTEM_TYPE":"Gas Gathering                 ","STATUS":"In Service","COUNTY_FIPS":"419","OBJECTID":114029,"COUNTY_NAME":"SHELBY","SHAPE.LEN":16.530275254816498,"P5_NUM":"775854"},"geometry":{"type":"LineString","coordinates":[[-94.37263800261006,31.776053575981486],[-94.37263747379711,31.776008115196802]],"bbox":[-94.37263800261006,31.776008115196802,-94.37263747379711,31.776053575981486]}}

I've naively written

    cat Pipelines.ndjson | ndjson-filter 'd.DIAMETER == "14"'

but this line gives me no output. What's my error?

**Comment by mbostock** [comment]
Try

```
ndjson-filter 'd.properties.DIAMETER === 14'
```
